# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1
# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: sakharuk/kbot.git
  tag: "v1.0.9-16664c0"
  arch: amd64
  os: linux
secret:
  name: kbot"
  tokenName: TELE_TOKEN
  tokenKey: token
securityContext:
  privileged: true
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
